### ISSUE TITLE
eth.Transaction: EIP-4844 Blob Txs (type 0x3)

### ISSUE THREAD

**Issue by ryanschneider** [INFURA/go-ethlibs#89]
https://eips.ethereum.org/EIPS/eip-4844#blob-transaction

We introduce a new [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) transaction, “blob transaction”, where the TransactionType is `BLOB_TX_TYPE` (0x03) and the `TransactionPayload` is the RLP serialization of the following `TransactionPayloadBody`:

```
[chain_id, nonce, max_priority_fee_per_gas, max_fee_per_gas, gas_limit, to, value, data, access_list, max_fee_per_blob_gas, blob_versioned_hashes, y_parity, r, s]
```

The field `to` deviates slightly from the semantics with the exception that it MUST NOT be nil and therefore must always represent a 20-byte address. This means that blob transactions cannot have the form of a create transaction.

The field `max_fee_per_blob_gas` is a uint256 and the field `blob_versioned_hashes` represents a list of hash outputs from kzg_to_versioned_hash.

The [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) ReceiptPayload for this transaction is `rlp([status, cumulative_transaction_gas_used, logs_bloom, logs])`.

**Comment by noleto** [comment]
@ElhadiCherifi95 @ggiannos when EIP-4844 will be deployed, transactions data structure will come with two new fields so we need to update our txs decoder in Python (https://github.com/INFURA/datasci-infra/blob/staging/business/spark/commons/tlm_commons/transaction_raw_decoder.py#L94)

(posting this message here as I reminder when transaction_from_raw.go will be updated :-)
